"""add bot_settings table

Revision ID: 5c1c6f1c6345
Revises: 83a3c983eb6f
Create Date: 2026-06-24 14:23:52.256887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1c6f1c6345'
down_revision: Union[str, Sequence[str], None] = '83a3c983eb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_settings_key'))

    op.drop_table('bot_settings')
    # ### end Alembic commands ###
