"""remove daily_limit from users

Revision ID: c3fa5a968749
Revises: 5c1c6f1c6345
Create Date: 2026-06-24 15:33:46.159728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fa5a968749'
down_revision: Union[str, Sequence[str], None] = '5c1c6f1c6345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_limit')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_limit', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
